import yag
x=int(input("enter first number : "))
y=int(input("enter second number : "))
print("addition is : ",yag.add(x,y))
print("subtrack is : ",yag.sub(x,y))
print("divion is : ",yag.div(x,y))
print("multiplition is : ",yag.mul(x,y))
print("modulo  is : ",yag.module(x,y))
print("sequre of ",x," is : ",yag.seq(x))
print("sequre of ",y," is : ",yag.seq(y))
print("factorial of ",x,"is : ",yag.fact(x))
print("factorial of ",y,"is : ",yag.fact(y))